### ISSUE TITLE
Compatability with Outlaws listed as a feature, not actually implemented yet

### ISSUE THREAD

**Issue by chaosvolt** [luciusDXL/TheForceEngine#112]
![image](https://user-images.githubusercontent.com/11582235/166614845-88866d64-af66-4be4-8a68-5a779bcdf6e5.png)

If the source port is not yet compatible with a game, then do not plaster the names of both games over every page as though it was currently a functional feature. This appears to be the only reference to the feature apparently being non-functional:
![image](https://user-images.githubusercontent.com/11582235/166614606-80abd871-d700-4543-ac14-aeefef097194.png)

If it is actually usable with Outlaws then the manual should be updated, but it should also be selectable in the game menu. Testing so far found that updating the config file to set the selected game to Outlaws does not function, and no mention can be found in the manual of how the feature is actually implemented.

If it isn't implemented, as indicated far down on the main page (after SEVERAL mentions of Outlaws as though it was currently functional), then it should not be repeatedly listed on every bit of the front page and manual, with the clarification that only Dark Forces is actually supported buried under paragraphs of wording implying that it is.

---

In particular, the phrase "Dark Forces and Outlaws" is mentioned as if they were compatible in the "about" section, mentioned twice in bold in the first paragraph of the readme, then again in the second paragraph plus a mention of level editor support, then a mention that only implies they don't have full the source code for Outlaws yet, then this sentence latter on: **It is much more focused than the XL Engine, focused on being a Jedi Engine replacement/port only - thus full support for Dark Forces and Outlaws.**

It's only on the eighth paragraph that this is clarified: "Outlaws support is at "tech demo" status - mainly so that the new Jedi Engine features are in-place even if Outlaws gameplay code is not yet ready."

Seems kinda massively jumping the gun at best, blatantly misleading at worst.

**Comment by luciusDXL** [comment]
Fair enough. It was meant to describe what the project is about and its goals. TFE is still a work in progress and even Dark Forces support is technically not complete yet. The reason Outlaws is not selectable is because it isn't playable, when it is playable it will be selectable.

Even in the first line it says "The Force Engine is a project to reverse engineer and rebuild the Jedi Engine..." and then describes why that is useful (ease of use features, controls, etc.).  In fact, if you read under "Current State" - https://theforceengine.github.io/ - you will see it is still in a **pre-release state**.

Regardless, I will update the documentation with the upcoming 0.9 release and remove the confusing mentions of Outlaws. But I will not remove the part about the **goal** of the project being to support both Dark Forces and Outlaws, even if that isn't the current reality. Full Dark Forces support is version 1.0 and Outlaws version 2.0, though I expect the time between 1.0 to 2.0 to be much shorter since both games share a lot of code.

**Comment by chaosvolt** [comment]
No worries then, mentioning what it plans to be and being more clear about what it can currently do seems fitting. A lot of the wording gave the impression that more of it was functional than what it can currently do.

**Comment by luciusDXL** [comment]
The wording has been changed to clearly indicate the Outlaws is not playable yet but that support is planned.
