### ISSUE TITLE
FOV change?

### ISSUE THREAD

**Issue by Joachim-Otahal** [luciusDXL/TheForceEngine#158]
Simple question: Can FOV be changed? settings.ini doesn't offer such setting.

**Comment by luciusDXL** [comment]
The FOV cannot be directly changed currently. The reason is that the original code makes assumptions about the vertical FOV that have not been corrected yet. The horizontal FOV is automatically adjusted for widescreen and ultrawide, however.

Adding support for changing the FOV will be added in a future update.

**Comment by luciusDXL** [comment]
The question has been answered, so I'm going to close this.

**Comment by Joachim-Otahal** [comment]
Thank you for that very fast response!
