### ISSUE TITLE
Mission 3 Objective and Reset Glitch?

### ISSUE THREAD

**Issue by paulrrogers** [luciusDXL/TheForceEngine#174]
Did something of a speed run with a new agent, just playing quickly though each mission back-to-back; not using exploits, tooling, or even the community patch this time around. Yet when playing mission 3 (sewers) I forgot to flip the switch for gate 1, somehow flipped switch 2, then 3. I believe I quick saved at this point.

[quicksave.zip](https://github.com/luciusDXL/TheForceEngine/files/10325938/quicksave.zip)

Then realized I missed the first switch, and the objective screen of PDA didn't register any objectives complete. Finally I flipped the first switch and was able to find Rebus despite no objectives completed in PDA. Strangely though when pressing Esc in front of Rebus the game reset (revived?) me to the jump before Rebus's double blast doors. Now my health was low as I'd run out of ammo, though I don't believe I was killed. Game still showed mission complete so after pressing Esc again I was able to leave and start mission 4.

**Comment by luciusDXL** [comment]
There is only one objective in this map - that is to find Rebus. So are you saying that you could complete the level before finding him or that the objective wasn't filled in the PDA after finding him? Otherwise it sounds like it is working as intended.

The game won't reset you to a previous check point unless you die, so I'm pretty sure you found Rebus and then died. But once you find him, the mission is complete so you can move on at any point after that - even if you die.

**Comment by Karjala22** [comment]
If you have more than one objectivein Mission 3 that means you are using the Community Patch. I wrote those new objectives and the only way to break them was to use cheats and skip to Rebus without pressing the switches. Do note - this is outside the realm of TFE suport - you should post them in DF-21's discord here [](https://discord.gg/6T9NvMh2MC)

**Comment by luciusDXL** [comment]
I don't think this is a TFE issue, so I'm closing.
