### ISSUE TITLE
[Feature Request] Please add build-in clip/fly feature from XL_Engine

### ISSUE THREAD

**Issue by KOK12X** [luciusDXL/TheForceEngine#368]
First at all,  dear lucius , thank you for your great work（both TheForceEngine and XL_Engine） !

The TheForceEngine have better game performance than XL_Engine, except：

1 no build-in clip/fly cheat feature , in XL_Engine, the player can hold "F"  or  "G"  key to active clip/fly cheat feature , and it is really useful to skip some boring platform-jumping or puzzle-sloved sequence

2 when run TheForceEngine, the cpu useage is as high as 28% （intel i5 11400）

if i run XL_Engine, the cpu useage is just 15%

so is there a way to decrease TheForceEngine's cpu useage？

sorry for my poor English（it is not my mother tongue T-T）

**Comment by luciusDXL** [comment]
You can already enable flying or no clip in TFE by using cheat codes:
LAFLY and LANOCLIP.

Once flying jump moves up and crouch moves down.

As for CPU usage, the best way is to enable vsync or set the frame limiter to the desired framerate. Beyond that, TFE is a reverse-engineered port, unlike DarkXL, so any differences in CPU performance are likely related to differences caused by that. Its the price for accurate behavior. :)
