### ISSUE TITLE
[Feature] EmScripten/WASM target

### ISSUE THREAD

**Issue by mlauss2** [luciusDXL/TheForceEngine#436]
Make it possible to run TFE in a browser using emscripten.
Since the only necessary external dependencies are SDL2 and SDL2-image, it should be possible to create a TFE port for WASM/WebGL using EmScripten.

I'm currently working on this.

**Comment by luciusDXL** [comment]
I'm on the fence about this one, mainly because dealing with WebGL is a can of worms and I eventually want to support compute shaders, etc. on higher end hardware (I am planning a GPU compute-based renderer at some point, as an option, that moves all of the CPU renderer work over to the GPU and removes most of the CPU/GPU bandwidth requirements).
